modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/thrasosc/mythos-bestiary-mod/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "mythos_bestiary"
version = "${version}"
displayName = "Mythos Bestiary"
displayURL="https://www.curseforge.com/minecraft/mc-mods/mythos-bestiary"
authors = "Thrasos"
description = '''
Bring Ancient Greek Creatures to Life
'''
logoFile = "icon.png"

[[dependencies.mythos_bestiary]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "azurelib"
type = "required"
versionRange = "[3.0.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mythos_bestiary.mixins.json"
