modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "GNU GPL 3.0"

[[mods]]
modId = "mythos_bestiary"
version = "${version}"
displayName = "Mythos Bestiary"
authors = "Thrasos"
description = '''
Bring Ancient Greek Creatures to Life
'''
#logoFile = ""

[[dependencies.mythos_bestiary]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mythos_bestiary]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "mythos_bestiary.mixins.json"
